# Generated by Django 2.2.24 on 2024-08-06 21:18

from django.db import migrations
import phonenumbers


def normalize_flat_phonenumbers(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.all().iterator():
        number_parse = phonenumbers.parse(flat.owners_phonenumber, "RU")
        final_number = phonenumbers.format_number(
            number_parse, phonenumbers.PhoneNumberFormat.E164
        )
        flat.owner_pure_phone = final_number
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0007_auto_20240818_1634"),
    ]

    operations = [
        migrations.RunPython(normalize_flat_phonenumbers),
    ]
